apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ['sh', '-c', 'while true; do date >> /data/output.txt; sleep 5; done']
        volumeMounts:
        - name: safedata
          mountPath: /data
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
        volumeMounts:
        - name: safedata
          mountPath: /data
      volumes:
      - name: safedata
        persistentVolumeClaim:
          claimName: pvc1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  namespace: homework
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/pv1/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: homework
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi


