apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nfs
  labels:
    app: nfs-app
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: vol-nfs
          mountPath: /nfs-share
      volumes:
      - name: vol-nfs
        persistentVolumeClaim:
          claimName: nfs

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi